---
title: "Data preparation"
author: "Jose J. Morosoli"
date: "2025-01-21"
output: html_document
---

# Index

The current document describes:

1. Computing new variables and creating data sets for analysis.

## Section 1: New variables and data sets.


```{r echo=T, results='hide', error=F, warning=F, message=F, eval=F}
# Load packages
library(foreign)

# Create an object to store the file path
file_path <- "path/to/your/GENDAC_PINGAULT_mcs_cm_structure_2021_05_12.sav"

# Load MCS data
CMstructure <- read.spss(file_path, to.data.frame=TRUE)

# Extract internalising and externalising subscales
internal_raw <- subset(CMstructure, select = c(Pingault_ID,BEMOTION,BPEER,CEMOTION,CPEER,DDEMOTION,DDPEER,FEMOTION,FPEER))
external_raw <- subset(CMstructure, select =c(Pingault_ID,BCONDUCT,BHYPER,CCONDUCT,CHYPER,DDCONDUCT,DDHYPER,FCONDUCT,FHYPER))

# Remove erroneous spaces in data using excel, and re-import
internal1 <- internal_raw
external1 <- external_raw
internal1$Pingault_ID <- gsub(gsub('PNG_05A35003UD','',internal_raw$Pingault_ID[1]),'', internal_raw$Pingault_ID)
external1$Pingault_ID <- gsub(gsub('PNG_05A35003UD','',external_raw$Pingault_ID[1]),'', external_raw$Pingault_ID)

# Make factors numeric characters
internal1$BEMOTION <- as.numeric(as.character(internal1$BEMOTION))
internal1$BPEER <- as.numeric(as.character(internal1$BPEER))
internal1$CEMOTION <- as.numeric(as.character(internal1$CEMOTION))
internal1$CPEER <- as.numeric(as.character(internal1$CPEER))
internal1$DDEMOTION <- as.numeric(as.character(internal1$DDEMOTION))
internal1$DDPEER <- as.numeric(as.character(internal1$DDPEER))
internal1$FEMOTION <- as.numeric(as.character(internal1$FEMOTION))
internal1$FPEER <- as.numeric(as.character(internal1$FPEER))
external1$BCONDUCT <- as.numeric(as.character(external1$BCONDUCT))
external1$BHYPER <- as.numeric(as.character(external1$BHYPER))
external1$CCONDUCT <- as.numeric(as.character(external1$CCONDUCT))
external1$CHYPER <- as.numeric(as.character(external1$CHYPER))
external1$DDHYPER <- as.numeric(as.character(external1$DDHYPER))
external1$DDHYPER <- as.numeric(as.character(external1$DDHYPER))
external1$FCONDUCT <- as.numeric(as.character(external1$FCONDUCT))
external1$FHYPER <- as.numeric(as.character(external1$FHYPER))

# Sum subscales to make internalising and externalising factors per sweep
internal1$BINT <- internal1$BEMOTION + internal1$BPEER
internal1$CINT <- internal1$CEMOTION + internal1$CPEER
internal1$DINT <- internal1$DDEMOTION + internal1$DDPEER
internal1$FINT <- internal1$FEMOTION + internal1$FPEER
external1$BEXT <- external1$BCONDUCT + external1$BHYPER
external1$CEXT <- external1$CCONDUCT + external1$CHYPER
external1$DEXT <- external1$DDCONDUCT + external1$DDHYPER
external1$FEXT <- external1$FCONDUCT + external1$FHYPER

# Merge int and ext scores
INTEXT <- merge(internal1, external1, by="Pingault_ID")
myData <- merge(all_data_PSPC, INTEXT, by.x="CM_ID", by.y="Pingault_ID")
myData <- merge(myData, SDQ, by.x="CM_ID", by.y="Pingault_ID")


```

## Standardise variables within time point

```{r echo=T, results='hide', error=F, warning=F, message=F, eval=F}

# Notes:
# Males = 1; Females = 0

# TASK 1: Standardise variables #

myData$zBINT <- scale(myData$BINT, center = T, scale = T)
myData$zCINT <- scale(myData$CINT, center = T, scale = T)
myData$zDINT <- scale(myData$DINT, center = T, scale = T)
myData$zFINT <- scale(myData$FINT, center = T, scale = T)

myData$zBEXT <- scale(myData$BEXT, center = T, scale = T)
myData$zCEXT <- scale(myData$CEXT, center = T, scale = T)
myData$zDEXT <- scale(myData$DEXT, center = T, scale = T)
myData$zFEXT <- scale(myData$FEXT, center = T, scale = T)

```

## Create cross clinical threshold (>=15) variable

```{r echo=T, results='hide', error=F, warning=F, message=F, eval=F}

myData$BCCT <- 0; myData$BCCT[myData$BEBDTOT>=15] <- 1  
myData$CCCT <- 0; myData$CCCT[myData$CEBDTOT>=15] <- 1
myData$DCCT <- 0; myData$DCCT[myData$DDDEBDTOT>=15] <- 1
myData$FCCT <- 0; myData$FCCT[myData$FEBDTOT>=15] <- 1

table(myData$BCCT[myData$SEX==0])/sum(table(myData$BCCT[myData$SEX==0]))*100
table(myData$CCCT[myData$SEX==0])/sum(table(myData$CCCT[myData$SEX==0]))*100
table(myData$DCCT[myData$SEX==0])/sum(table(myData$DCCT[myData$SEX==0]))*100
table(myData$FCCT[myData$SEX==0])/sum(table(myData$FCCT[myData$SEX==0]))*100

table(myData$BCCT[myData$SEX==1])/sum(table(myData$BCCT[myData$SEX==1]))*100
table(myData$CCCT[myData$SEX==1])/sum(table(myData$CCCT[myData$SEX==1]))*100
table(myData$DCCT[myData$SEX==1])/sum(table(myData$DCCT[myData$SEX==1]))*100
table(myData$FCCT[myData$SEX==1])/sum(table(myData$FCCT[myData$SEX==1]))*100
```

## Obtain means and standard deviations by sex

```{r echo=T, results='hide', error=F, warning=F, message=F, eval=F}
# Load libraries
library(psych)

describeBy(myData[,c('BEBDTOT','CEBDTOT','DDDEBDTOT','FEBDTOT')], group = myData$SEX)
describeBy(myData[,c('BEXT','CEXT','DEXT','FEXT')], group = myData$SEX)
describeBy(myData[,c('BINT','CINT','DINT','FINT')], group = myData$SEX)

```

